### PR TITLE
Create model Store with Admin association and validations

### PR DESCRIPTION
**Pull request by d1eg0dev**
Validations for name and address fields
Migration store table

Co-authored-by: d1eg0dev <diego@studiowd.com.mx>
Co-authored-by: EdwardMD <Edwardmi444@gmail.com>
Co-authored-by: carlos-ssh <carlos.anezeh@gmail.com>
Co-authored-by: Ever <ever864@gmail.com>

### CODE REVIEW

**Review by carlos-ssh — APPROVED** [review]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi <STUDENT_MENTION>, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Approved


Cheers and Happy coding!👏👏👏

**Review by ever864 — APPROVED** [review]
Me parece genial las validaciones que hiciste en el modelo Store, y el proyecto en general!

**Review by EdwardMD — APPROVED** [review]
very good pull, making more and more progress

**Comment by HikingCarrot7** [comment]
LGTM!

**Pull request merged**
