### PR TITLE
Feature#57 setup kaminary add its styles

### PR DESCRIPTION
**Pull request by ever864**
-Add boolean button for each employee (deactivate and active).
-Refactoring style in navbar/dashboard and login devise.
-Improve searching for all employees.
-Add search form for attendance for a specific date.

### CODE REVIEW

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by V-Juarez — APPROVED** [review]

**Review by lucasvidela94 — APPROVED** [review]
LGTM! 🍝

**Review by HikingCarrot7 — APPROVED** [review]
LGTM

**Review by EdwardMD — COMMENTED** [review]
LGTM!

**Review by acorzo — APPROVED** [review]
Good Joob 👍

**Pull request merged**
