### PR TITLE
Feature#55 setup cloudinary and styles

### PR DESCRIPTION
**Pull request by ever864**
- Setup cloudinary gem
- Add styles for image profile in index view for dashboard controller.

### CODE REVIEW

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by OwenLobato — APPROVED** [review]
LGTM

**Review by guillermo-delprado — APPROVED** [review]
LGTM! :)

**Review by lucasvidela94 — APPROVED** [review]
LGTM!

**Pull request merged**
